version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    container_name: redis
    image: redis:7.0.4-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/usr/local/etc/redis

volumes:
  mysql_data:
  redis_data:
